### ISSUE TITLE
ResolveTypeInContext sample throws an exception

### ISSUE THREAD

**Issue by peteruhnak** [javaparser/javaparser-visited#28] opened 2021-10-24 13:07 UTC
The example for `ResolveTypeInContext` in the book throws an exception

> [reflectionTypeSolver.setParent(reflectionTypeSolver);](https://github.com/javaparser/javaparser-visited/blob/master/src/main/java/org/javaparser/examples/chapter5/ResolveTypeInContext.java#L23)

```
Exception in thread "main" java.lang.IllegalStateException: The parent of this TypeSolver cannot be itself.
	at com.github.javaparser.symbolsolver.resolution.typesolvers.ClassLoaderTypeSolver.setParent(ClassLoaderTypeSolver.java:60)
```

Presumably the line should be removed (as the parent is overridden anyway from `combinedSolver.add(reflectionTypeSolver)`

(also in the same example `Navigator.findNodeOfGivenClass(cu, FieldDeclaration.class);` is deprecated

**Comment by abego** [comment] 2022-07-17 21:34
May be a duplicate of https://github.com/javaparser/javaparser-visited/issues/28

**Comment by SmiddyPence** [comment] 2023-07-21 15:03
Thanks for the report. 

Should be resolved with latest changes to book and samples.

**Closed by SmiddyPence** 2023-07-21 15:03 UTC
